In [2]:
from tensorflow.keras.preprocessing.text import one_hot


In [ ]:
### sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

### vocabulary size
voc_size = 10000

In [7]:
# One hot representation
onehot_repr = [one_hot(sentence, voc_size) for sentence in sent]
onehot_repr

[[2618, 3969, 1122, 6722],
 [2618, 3969, 1122, 96],
 [2618, 7610, 1122, 6166],
 [3402, 2056, 6054, 1658, 1187],
 [3402, 2056, 6054, 1658, 6904],
 [5834, 2618, 5439, 1122, 9706],
 [3042, 4826, 1321, 1658]]

In [9]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [11]:
sent_len = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_len)
embedded_docs

array([[   0,    0,    0,    0, 2618, 3969, 1122, 6722],
       [   0,    0,    0,    0, 2618, 3969, 1122,   96],
       [   0,    0,    0,    0, 2618, 7610, 1122, 6166],
       [   0,    0,    0, 3402, 2056, 6054, 1658, 1187],
       [   0,    0,    0, 3402, 2056, 6054, 1658, 6904],
       [   0,    0,    0, 5834, 2618, 5439, 1122, 9706],
       [   0,    0,    0,    0, 3042, 4826, 1321, 1658]], dtype=int32)

In [12]:
# Feature Repr
dim =10

In [23]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_len,) ))
model.compile('adam', 'mse')

c:\Users\Danns\OneDrive\Desktop\Udemy_GenAI\Projects\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [24]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step


array([[[ 0.00537822, -0.02649572, -0.01055779, -0.02916423,
         -0.04791616, -0.02624961, -0.02897251,  0.04661943,
          0.03988378,  0.04066211],
        [ 0.00537822, -0.02649572, -0.01055779, -0.02916423,
         -0.04791616, -0.02624961, -0.02897251,  0.04661943,
          0.03988378,  0.04066211],
        [ 0.00537822, -0.02649572, -0.01055779, -0.02916423,
         -0.04791616, -0.02624961, -0.02897251,  0.04661943,
          0.03988378,  0.04066211],
        [ 0.00537822, -0.02649572, -0.01055779, -0.02916423,
         -0.04791616, -0.02624961, -0.02897251,  0.04661943,
          0.03988378,  0.04066211],
        [ 0.01239   , -0.01606832, -0.04237909,  0.03131148,
         -0.01905488,  0.02152191,  0.04507541, -0.00692283,
         -0.01618486,  0.01357938],
        [ 0.01737439, -0.02179806, -0.00873638, -0.02738618,
         -0.02094721, -0.03397286, -0.0382765 , -0.01100892,
          0.01718256,  0.04139395],
        [ 0.04999025, -0.0227375 ,  0.03563548, -0.0

In [27]:
embedded_docs[0]

array([   0,    0,    0,    0, 2618, 3969, 1122, 6722], dtype=int32)